# Generated by Django 3.1.4 on 2020-12-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
