# Generated by Django 3.1.4 on 2020-12-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20201201_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceTypes',
            new_name='ServiceType',
        ),
    ]
