# Generated by Django 3.1.4 on 2020-12-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_auto_20201201_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='geometry',
            field=models.JSONField(verbose_name='Область'),
        ),
    ]
