# Generated by Django 3.1.4 on 2020-12-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_auto_20201201_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearea',
            name='price',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='service_types',
        ),
        migrations.CreateModel(
            name='AreaService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='цена обслуживания за единицу оказываемой услуги')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areaservice', to='suppliers.servicearea')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areaservice', to='suppliers.servicetype')),
            ],
        ),
        migrations.AddField(
            model_name='servicearea',
            name='services',
            field=models.ManyToManyField(through='suppliers.AreaService', to='suppliers.ServiceType', verbose_name='Типы обслуживания'),
        ),
    ]
