# Generated by Django 3.1.4 on 2020-12-03 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_auto_20201202_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='цена обслуживания за единицу оказываемой услуги')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeinarea', to='suppliers.servicearea')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeinarea', to='suppliers.servicetype')),
            ],
        ),
        migrations.DeleteModel(
            name='AreaService',
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='services',
            field=models.ManyToManyField(through='suppliers.TypeInArea', to='suppliers.ServiceType', verbose_name='Типы обслуживания'),
        ),
    ]
